name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            target: linux
          - os: macos-latest
            target: macos
          - os: windows-latest
            target: windows

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build
        run: |
          if [ "${{ matrix.target }}" = "windows" ]; then
            choco install mingw
            make clean
            make cross
          else
            make clean
            make
          fi

      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: findaes-${{ matrix.target }}
          path: findaes${{ matrix.target == 'windows' && '.exe' || '' }}
